### ISSUE TITLE
Add basic UI to the app 

### ISSUE THREAD

**Issue by atm1504** [NJACKWinterOfCode/Github_Profile_APP#2]
Add basic ui to the app.
It should have an edit text to take input the GitHub username, then a button clicking on which would fetch the details of that user name

**Comment by Ashish0077** [comment]
can i work on this?

**Comment by atm1504** [comment]
@Ashish0077 u can work on this after #1  is solved
Till then u can start with https://github.com/NJACKWinterOfCode/IITPConfessionsApp/issues/1

**Comment by Mehulipal** [comment]
Can I start working on it now?

**Comment by atm1504** [comment]
yes

**Comment by Mehulipal** [comment]
On clicking button,exactly what details should the user visualize?
Can you please elaborate a bit...

**Comment by atm1504** [comment]
@Mehulipal 
First: Create a sub-issue. In which add a fragment that asks for user GitHub id and a button.
Clicking on the button would fetch user details. This data would be shown in a different fragment. In that fragment for now show the Name, bio, profile image of the user. Other details can be added slowly. Subdivide the task and start the work.

**Comment by Mehulipal** [comment]
Ok

**Comment by parth222** [comment]
can i work on this?
